config/routes.rb
Rails.application.routes.draw do

  devise_for :reviewers, controllers: { registrations: "reviewers/registrations" }
  resources :reviewers

  resources :analytics

  resources :domains

  devise_for :clerks, controllers: { registrations: "clerks/registrations" }
  resources :clerks

  resources :demos

  devise_for :admins, controllers: { registrations: "admins/registrations" }

  resources :photos

  resources :schools

  resources :photo_links

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :articles

  resources :users do 
    resources :tags
  end

  resources :background_infos
  resources :experiences
  resources :homepage_infos
  resources :personal_infos
  resources :projects
  resources :showcases
  resources :social_links
  resources :website_settings
  resources :photos
  resources :schools

  get 'tags/:tag', to: 'schools/#{school.id}/#students', as: :tag ## Don't think this is doing anything??

  resources :users do 
    get '/feed', to: 'users#feed', as: :feed
    get '/dashboard', to: 'users#dashboard', as: :dashboard
    resources :after_signup, controller: 'users/after_signup'
  end

  resources :schools do
    get '/roster', to: 'schools#roster', as: :roster
  end

  resources :personal_infos do
    get 'crop', to: 'personal_infos/#crop', as: :crop
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    case user
    when User
        can :manage, User, :id => user.id
        can :manage, HomepageInfo, :user_id => user.id
        can :manage, BackgroundInfo, :user_id => user.id
        can :manage, PersonalInfo, :user_id => user.id
        can :manage, PhotoLink, :user_id => user.id
        can :manage, Showcase, :user_id => user.id
        can :manage, Project, :user_id => user.id
        can :manage, Photo, :user_id => user.id
        can :manage, SocialLink, :user_id => user.id
        can :manage, WebsiteSetting, :user_id => user.id
        can :manage, Domain, :user_id => user.id
        can :manage, Analytic, :user_id => user.id
        can [:show, :create], Analytic

        can :manage, Article, :user => { :id => user.id }
        can :manage, Experience, :background_info => { :user_id => user.id }

    when Admin
        can :manage, User
        can :manage, Admin
        can :manage, HomepageInfo
        can :manage, BackgroundInfo
        can :manage, PersonalInfo
        can :manage, PhotoLink
        can :manage, Showcase
        can :manage, Project
        can :manage, Photo
        can :manage, SocialLink
        can :manage, WebsiteSetting
        can :manage, Article
        can :manage, Experience
        can :manage, Domain
        can :manage, Analytic
        can :manage, School
        can :manage, Clerk
        can :manage, Reviewer

    when Clerk
        can :manage, User, :school_id => user.school_id
        can :manage, Clerk, :id => user.id

    when Reviewer
        can :manage, User, :school_id => user.school_id
        can :manage, Reviewer, :id => user.id

    end
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
end

app/models/balance.rb
class Balance < ActiveRecord::Base
end

app/models/career.rb
class Career < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/clerk.rb
class Clerk < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :school
  has_many :users, through: :school
end

app/models/demo.rb
class Demo < ActiveRecord::Base
end

app/models/domain.rb
class Domain < ActiveRecord::Base
	belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user

	has_attached_file :file1
	has_attached_file :file2
	has_attached_file :file3
	has_attached_file :file4

	do_not_validate_attachment_file_type :file1
	do_not_validate_attachment_file_type :file2
	do_not_validate_attachment_file_type :file3
	do_not_validate_attachment_file_type :file4
end

app/models/region.rb
class Region < ActiveRecord::Base
end

app/models/reviewer.rb
class Reviewer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	belongs_to :school
	has_many :users, through: :school
end

app/models/school.rb
class School < ActiveRecord::Base
	has_many :users
	has_many :clerks
	has_many :projects, through: :users
	has_many :articles, through: :users
	has_many :photos, through: :users

	has_attached_file :logo, styles: { med: "300x300>", small: "100x100>", large: "600x600>"}
	validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/

	default_scope { order('name ASC') }
end

app/models/sex.rb
class Sex < ActiveRecord::Base
end

app/models/size.rb
class Size < ActiveRecord::Base
end

app/models/skill.rb
class Skill < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/travel.rb
class Travel < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :articles,  autosave: true
	has_one :background_info,  autosave: true
	has_many :experiences, through: :background_info
	has_one :homepage_info,  autosave: true
	has_one :personal_info,  autosave: true
	has_one :photo_link,  autosave: true
	has_many :projects, autosave: true
	has_one :social_link,  autosave: true
	has_one :website_setting,  autosave: true
	has_one :domain,  autosave: true
	has_one :analytic,  autosave: true

	has_many :photos, autosave: true

	belongs_to :school

	include ActiveModel::Validations
	validates_with GoodnessValidator

	acts_as_taggable
	acts_as_taggable_on :industry, :career, :language, :wexperience, :undergrad, :uconcentration, :travel, :state, :skill, :size, :sex, :region, :mconcentration, :demographic, :balance, :visa, :city
	scope :by_join_date, order("created_at DESC")

	# validate :maximum_amount_of_tags


	def maximum_amount_of_tags
		number_of_tags = tag_list_cache_on("sex").uniq.length
		errors.add(:base, "Please only select 1 gender") if number_of_tags > 1
	end
	
end

app/models/visa.rb
class Visa < ActiveRecord::Base
end

app/controllers/reviewers/registrations_controller.rb
class Reviewers::RegistrationsController < Devise::RegistrationsController
  # disable default no_authentication action
  skip_before_action :require_no_authentication, only: [:new, :create, :cancel]

  # now we need admin to register new reviwer
  # prepend_before_action :authenticate_scope!, only: [:new, :create, :cancel]

  protected

  def sign_up(resource_name, resource)
    # just overwrite the default one
    # to prevent auto sign in as the new sign up
  end

  def after_sign_up_path_for(resource)
    # 
  end
end

app/controllers/reviewers_controller.rb
class ReviewersController < ApplicationController
  before_action :set_reviewer, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @reviewers = Reviewer.all
    respond_with(@reviewers)
  end

  def show
    respond_with(@reviewer)
  end

  def new
    @reviewer = Reviewer.new
    respond_with(@reviewer)
  end

  def edit
  end

  def create
    @reviewer = Reviewer.new(reviewer_params)
    @reviewer.save
    respond_with(@reviewer)
  end

  def update
    @reviewer.update(reviewer_params)
    respond_with(@reviewer)
  end

  def destroy
    @reviewer.destroy
    respond_with(@reviewer)
  end

  private
    def set_reviewer
      @reviewer = Reviewer.find(params[:id])
    end

    def reviewer_params
      params[:reviewer].permit(:school_id)
    end
end

app/helpers/reviewers_helper.rb
module ReviewersHelper
end

app/views/reviewers/_form.html.erb
<%= simple_form_for(@reviewer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reviewers/edit.html.erb
<h1>Editing reviewer</h1>

<%= render 'form' %>

<%= link_to 'Show', @reviewer %> |
<%= link_to 'Back', reviewers_path %>

app/views/reviewers/index.html.erb
<h1>Listing reviewers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviewers.each do |reviewer| %>
      <tr>
        <td><%= link_to 'Show', reviewer %></td>
        <td><%= link_to 'Edit', edit_reviewer_path(reviewer) %></td>
        <td><%= link_to 'Destroy', reviewer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reviewer', new_reviewer_path %>

app/views/reviewers/new.html.erb
<h1>New reviewer</h1>

<%= render 'form' %>

<%= link_to 'Back', reviewers_path %>

app/views/reviewers/show.html.erb
<div class = "small-12 medium-12 columns form-yield no-padding">
	<%= render 'application/topNavReviewers' %>
</div>
<div id = "clerk-nav-filler"></div>
<%= render 'application/alerts' %>


<div class = "row clerk-content-container">
	<div id="unapproved" style="display:none">
		<div class = "small-12 medium-12 columns small-centered">
			<% @students = @reviewer.users.where(:approval => 0) %>
			<%= render 'users/userReviewerViewUnapproved' %>
		</div>
	</div>

	<div id="reviewing">
		<div class = "small-12 medium-12 columns small-centered">
			<% @students = @reviewer.users.where(:approval => 1) %>
			<%= render 'users/userReviewerViewReviewing' %>
		</div>
	</div>

	<div id="pending" style="display:none">
		<div class = "small-12 medium-12 columns small-centered">
			<% @students = @reviewer.users.where(:approval => 2) %>
			<%= render 'users/userReviewerViewPending' %>
		</div>
	</div>

	<div id="approved" style="display:none">
		<div class = "small-12 medium-12 columns small-centered">
			<% @students = @reviewer.users.where(:approval => 3) %>
			<%= render 'users/userReviewerViewApproved' %>
		</div>
	</div>
</div>