config/routes.rb
Rails.application.routes.draw do

  devise_for :reviewers, controllers: { registrations: "reviewers/registrations" }
  resources :reviewers

  resources :analytics

  resources :domains

  devise_for :clerks, controllers: { registrations: "clerks/registrations" }
  resources :clerks

  resources :demos

  devise_for :admins, controllers: { registrations: "admins/registrations" }

  resources :photos

  resources :schools

  resources :photo_links

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :articles

  resources :users do 
    resources :tags
  end

  resources :background_infos
  resources :experiences
  resources :homepage_infos
  resources :personal_infos
  resources :projects
  resources :showcases
  resources :social_links
  resources :website_settings
  resources :photos
  resources :schools

  get 'tags/:tag', to: 'schools/#{school.id}/#students', as: :tag ## Don't think this is doing anything??

  resources :users do 
    get '/feed', to: 'users#feed', as: :feed
    get '/dashboard', to: 'users#dashboard', as: :dashboard
    resources :after_signup, controller: 'users/after_signup'
  end

  resources :schools do
    get '/roster', to: 'schools#roster', as: :roster
  end

  resources :personal_infos do
    get 'crop', to: 'personal_infos/#crop', as: :crop
  end

end

app/models/social_link.rb
class SocialLink < ActiveRecord::Base
	belongs_to :user
end

app/controllers/social_links_controller.rb
class SocialLinksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_social_link, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :except => [:create, :new]

  # GET /social_links
  # GET /social_links.json
  def index
    @social_links = SocialLink.all
  end

  # GET /social_links/1
  # GET /social_links/1.json
  def show
  end

  # GET /social_links/new
  def new
    @social_link = SocialLink.new
  end

  # GET /social_links/1/edit
  def edit
  end

  # POST /social_links
  # POST /social_links.json
  def create
    @social_link = current_user.create_social_link(social_link_params)
    respond_to do |format|
      if @social_link.save
          format.html { redirect_to edit_social_link_path(@social_link), notice: 'Social Links were successfully created.' }
          format.json { render :show, status: :created, location: @social_link }
      else
        format.html { render :new }
        format.json { render json: @social_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /social_links/1
  # PATCH/PUT /social_links/1.json
  def update
    respond_to do |format|
      if @social_link.update(social_link_params)
        format.html { redirect_to edit_social_link_path(@social_link), notice: 'Social link was successfully updated.' }
        format.json { render :show, status: :ok, location: @social_link }
      else
        format.html { render :edit }
        format.json { render json: @social_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /social_links/1
  # DELETE /social_links/1.json
  def destroy
    @social_link.destroy
    respond_to do |format|
      format.html { redirect_to edit_social_link_path(@social_link), notice: 'Social link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_social_link
      @social_link = SocialLink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def social_link_params
      params.require(:social_link).permit(:link_linkedin, :link_instagram, :link_facebook, :link_twitter, :link_tumblr, :link_github, :link_alt_email)
    end
end

app/helpers/social_links_helper.rb
module SocialLinksHelper
end

app/views/social_links/_form.html.erb
<%= simple_form_for(@social_link) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :link_alt_email, label: "Contact Email Address:", placeholder: "Login email used by default" %>
  	<%= f.input :link_linkedin, label: "LinkedIn Profile:", placeholder: "Include http://" %>
  	<%= f.input :link_instagram, label: "Instagram Profile:", placeholder: "Include http://" %>
  	<%= f.input :link_facebook, label: "Facebook Profile:", placeholder: "Include http://" %>
  	<%= f.input :link_twitter, label: "Twitter Profile:", placeholder: "Include http://" %>
  	<%= f.input :link_tumblr, label: "Tumblr Profile:", placeholder: "Include http://" %>
  	<%= f.input :link_github, label: "Github Profile:", placeholder: "Include http://" %>
  </div>

  <div class="form-actions">
   <%= f.button :submit, 'Save' %>
   <% if current_user.social_link != nil %>
     <a href="#" data-reveal-id="previewModal" class = "button alt3">View</a>
   <% end %>
   <a href="/website_settings/<%= current_user.website_setting.id %>/edit" class = "buttonNext"> Next  <i class="fa fa-arrow-right"></i> </a>
  </div>
<% end %>

app/views/social_links/edit.html.erb
<div class = "row edit-page">
    <%= render 'application/sideNav'%>
    <div class = "small-12 medium-9 columns form-yield no-padding">
        <%= render 'application/topNav' %>
        <%= render 'application/alerts' %>

        <div class = "small-12 medium-9 columns edit-content-section">
            <div class = "edit-info-header">
                <h4> Edit Social Links</h4>
                <a href="#" data-reveal-id="instructModal">
                    <i class="fa fa-info-circle"></i>&nbsp;Help
                </a>
            </div>
		<%= render 'form' %>
		<%= render 'application/instructions_social_links' %>
        <%= render 'application/preview_social_links' %>
	</div>
</div>

app/views/social_links/index.html.erb
<h1>Listing social_links</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @social_links.each do |social_link| %>
      <tr>
        <td><%= link_to 'Show', social_link %></td>
        <td><%= link_to 'Edit', edit_social_link_path(social_link) %></td>
        <td><%= link_to 'Destroy', social_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Social link', new_social_link_path %>

app/views/social_links/new.html.erb
<div class = "row edit-page">
    <%= render 'application/sideNav'%>
    <div class = "small-12 medium-9 columns form-yield no-padding">
        <%= render 'application/topNav' %>
        <%= render 'application/alerts' %>

        <div class = "small-12 medium-9 columns edit-content-section">
            <div class = "edit-info-header">
                <h4> Upload Social Links</h4>
                <a href="#" data-reveal-id="instructModal">
                    <i class="fa fa-info-circle"></i>&nbsp;Help
                </a>
            </div>
		<%= render 'form' %>
		<%= render 'application/instructions_social_links' %>
	</div>
</div>

app/views/social_links/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_social_link_path(@social_link) %> |
<%= link_to 'Back', social_links_path %>