config/routes.rb
Rails.application.routes.draw do

  devise_for :reviewers, controllers: { registrations: "reviewers/registrations" }
  resources :reviewers

  resources :analytics

  resources :domains

  devise_for :clerks, controllers: { registrations: "clerks/registrations" }
  resources :clerks

  resources :demos

  devise_for :admins, controllers: { registrations: "admins/registrations" }

  resources :photos

  resources :schools

  resources :photo_links

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :articles

  resources :users do 
    resources :tags
  end

  resources :background_infos
  resources :experiences
  resources :homepage_infos
  resources :personal_infos
  resources :projects
  resources :showcases
  resources :social_links
  resources :website_settings
  resources :photos
  resources :schools

  get 'tags/:tag', to: 'schools/#{school.id}/#students', as: :tag ## Don't think this is doing anything??

  resources :users do 
    get '/feed', to: 'users#feed', as: :feed
    get '/dashboard', to: 'users#dashboard', as: :dashboard
    resources :after_signup, controller: 'users/after_signup'
  end

  resources :schools do
    get '/roster', to: 'schools#roster', as: :roster
  end

  resources :personal_infos do
    get 'crop', to: 'personal_infos/#crop', as: :crop
  end

end

app/models/background_info.rb
class BackgroundInfo < ActiveRecord::Base
	belongs_to :user
	has_many :experiences
end

app/controllers/background_infos_controller.rb
class BackgroundInfosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_background_info, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :except => [:create, :new]

  # GET /background_infos
  # GET /background_infos.json
  def index
    @background_infos = BackgroundInfo.all
  end

  # GET /background_infos/1
  # GET /background_infos/1.json
  def show
  end

  # GET /background_infos/new
  def new
    @background_info = BackgroundInfo.new
  end

  # GET /background_infos/1/edit
  def edit
  end

  # POST /background_infos
  # POST /background_infos.json
  def create
    @user = current_user
    @background_info = @user.create_background_info(background_info_params)

    respond_to do |format|
      if @background_info.save
        format.html { redirect_to edit_background_info_path(@background_info), notice: 'Background info was successfully created.' }
        format.json { render :show, status: :created, location: @background_info }
      else
        format.html { render :new }
        format.json { render json: @background_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /background_infos/1
  # PATCH/PUT /background_infos/1.json
  def update
    @user = current_user
    respond_to do |format|
      if @background_info.update(background_info_params)
        format.html { redirect_to edit_background_info_path(@background_info), notice: 'Background info was successfully updated.' }
        format.json { render :show, status: :ok, location: @background_info }
      else
        format.html { render :edit }
        format.json { render json: @background_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /background_infos/1
  # DELETE /background_infos/1.json
  def destroy
    @background_info.destroy
    respond_to do |format|
      format.html { redirect_to background_infos_url, notice: 'Background info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_background_info
      @background_info = BackgroundInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def background_info_params
      params.require(:background_info).permit(:background_type)
    end
end

app/helpers/background_infos_helper.rb
module BackgroundInfosHelper
end

app/views/background_infos/_form.html.erb
<%= simple_form_for(@background_info) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<p class = "alt-text"> Do you want the title of this section to be 'Experience' or 'Education'? </p>
    <%= f.collection_radio_buttons :background_type, [[0, 'Experience'] ,[1, 'Education']], :first, :last%>
    <br/>
  </div>

  <div class="form-actions">
   <%= f.button :submit, 'Save' %>
   <a href="#" data-reveal-id="previewModal" class = "button alt3">Preview</a>
  </div>
<% end %>

app/views/background_infos/edit.html.erb
<div class = "row edit-page">
	<%= render 'application/sideNav'%>
	<div class = "small-12 medium-9 columns form-yield no-padding">
		<%= render 'application/topNav' %>
		<%= render 'application/alerts' %>

		<div class = "small-12 medium-9 columns edit-content-section">
			<div class = "edit-info-header">
				<h4> Edit Background Info </h4>
				<a href="#" data-reveal-id="instructModal">
					<i class="fa fa-info-circle"></i>&nbsp;Instructions
				</a>
			</div>

			<%= render 'form' %>
			<br/>
			<br/>
			<br/>

			<% if @background_info.background_type == 0 %>
			<h4 class = "edit-info-header"> Prior Experience </h4>
			<% else %>
			<h4 class = "edit-info-header"> Prior Education </h4>
			<% end %>
			<br/>

			<%= render @background_info.experiences.reverse %>
			<% if @background_info.experiences.count < 4 %>
			<% if @background_info.background_type == 0 %>
			<%= button_to "Add New Experience", new_experience_path, :class => "button", :method => :get %>
			<% else %>
			<%= button_to "Add New Education", new_experience_path, :class => "button", :method => :get %>
			<% end %>
			<% else %>
			<p class = "alt-text">Four is the maximum number of experiences. </p>
			<% end %>
			<br/>

			<%= render 'application/instructions_background_info' %>
			<%= render 'application/preview_background_info' %>

		</div>
	</div>
</div>

app/views/background_infos/index.html.erb
<h1>Listing background_infos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @background_infos.each do |background_info| %>
      <tr>
        <td><%= link_to 'Show', background_info %></td>
        <td><%= link_to 'Edit', edit_background_info_path(background_info) %></td>
        <td><%= link_to 'Destroy', background_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Background info', new_background_info_path %>

app/views/background_infos/new.html.erb
<div class = "row edit-page">
	<%= render 'application/sideNav'%>
	<div class = "small-12 medium-9 columns form-yield no-padding">
		<%= render 'application/topNav' %>
		<%= render 'application/alerts' %>

		<div class = "small-12 medium-9 columns edit-content-section">
			<div class = "edit-info-header">
				<h4> Edit Background Info </h4>
				<a href="#" data-reveal-id="instructModal">
					<i class="fa fa-info-circle"></i>&nbsp;Instructions
				</a>
			</div>

			<%= render 'form' %>

			<%= render 'application/instructions_background_info' %>

		</div>
	</div>
</div>

app/views/background_infos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_background_info_path(@background_info) %> |
<%= link_to 'Back', background_infos_path %>