config/routes.rb
Rails.application.routes.draw do

  devise_for :reviewers, controllers: { registrations: "reviewers/registrations" }
  resources :reviewers

  resources :analytics

  resources :domains

  devise_for :clerks, controllers: { registrations: "clerks/registrations" }
  resources :clerks

  resources :demos

  devise_for :admins, controllers: { registrations: "admins/registrations" }

  resources :photos

  resources :schools

  resources :photo_links

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :articles

  resources :users do 
    resources :tags
  end

  resources :background_infos
  resources :experiences
  resources :homepage_infos
  resources :personal_infos
  resources :projects
  resources :showcases
  resources :social_links
  resources :website_settings
  resources :photos
  resources :schools

  get 'tags/:tag', to: 'schools/#{school.id}/#students', as: :tag ## Don't think this is doing anything??

  resources :users do 
    get '/feed', to: 'users#feed', as: :feed
    get '/dashboard', to: 'users#dashboard', as: :dashboard
    resources :after_signup, controller: 'users/after_signup'
  end

  resources :schools do
    get '/roster', to: 'schools#roster', as: :roster
  end

  resources :personal_infos do
    get 'crop', to: 'personal_infos/#crop', as: :crop
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user

	has_attached_file :file1
	has_attached_file :file2
	has_attached_file :file3
	has_attached_file :file4

	do_not_validate_attachment_file_type :file1
	do_not_validate_attachment_file_type :file2
	do_not_validate_attachment_file_type :file3
	do_not_validate_attachment_file_type :file4
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :except => [:create, :new]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @user = current_user
    @project = @user.projects.create(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    @user = current_user
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @user = current_user
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_path, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :paragraph, :file1, :file2, :file3, :file4, :url, :file1_title, :file2_title, :file3_title, :file4_title, :file1_type, :file2_type, :file3_type, :file4_type)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :title %>
  	<%= f.input :paragraph %>
    <%= f.input :url %>
  	<%= f.input :file1 %>
  	<%= f.input :file2 %>
  	<%= f.input :file3 %>
  	<%= f.input :file4 %>
  </div>

  <div class="form-actions">
   <%= f.button :submit, 'Save' %>
  </div>
<% end %>

app/views/projects/_form0.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :title, placeholder: 'Data Analysis of Industry M&A' %>
  	<%= f.input :paragraph, placeholder: 'In my Corporate Finance class I conducted a project on.. ' %>
    <br/>
  	<%= f.input :file1 %>
    <%= f.input :file1_title %>
    <br/>
  	<%= f.input :file2 %>
    <%= f.input :file2_title %>
    <br/>
  	<%= f.input :file3 %>
    <%= f.input :file3_title %>
    <br/>
  	<%= f.input :file4 %>
    <%= f.input :file4_title %>
    <br/>
  </div>

  <div class="form-actions">
    <div class = "small-6 columns left">
     <%= f.button :submit, 'Save' %>
  </div>
  <div class = "small-6 columns right text-right">
    <br/>
      <a href="javascript:history.back()"> Cancel </a>
  </div>
<% end %>

app/views/projects/_form1.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :title, label: 'Title:', placeholder: "The Facebook" %>
  	<%= f.input :paragraph, label: 'Description:', placeholder: "Founder & CEO" %>
  	<%= f.input :file1, label: 'Background Image:' %>
    <br/>
    <p><i> You can have the project link to a website <strong>or</strong> a file: </i></p>
    <%= f.input :url, label: 'URL Link:' %>
    <p> <strong> OR </strong> </p>
    <%= f.input :file2, label: 'File Link:' %>
  </div>

  <div class="form-actions">
   <%= f.button :submit, 'Save' %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<%= project.title %><br/>

<small>
    <%= link_to 'Edit', edit_project_path(project) %> | 
    <%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' } %>
</small>
<br/>
<br/>
<br/>

app/views/projects/_project0.html.erb
<% @user.projects.each do |project| %>
          <div class = "row">
  <div class = "small-12 small-centered columns">
    <h4> <%= project.title %> </h4>
    <p> <%= simple_format(project.paragraph) %></p>

    <% if project.file1? %>
    <a href="<%= project.file1.url() %>">
      <% if project.file1_type == 0 %>
      <i class="fa fa-file-word-o fa-2x"></i> 
      <% elsif project.file1_type == 1 %>
      <i class="fa fa-file-excel-o fa-2x"></i> 
      <% elsif project.file1_type == 2 %>
      <i class="fa fa-file-powerpoint-o fa-2x"></i> 
      <% else %>
      <i class="fa fa-file-pdf-o fa-2x"></i> 
      <% end %>
      &nbsp; <%= project.file1_title %>
    </a><br/>
    <% end %>

    <% if project.file2? %>
    <a href="<%= project.file1.url() %>">
      <% if project.file2_type == 0 %>
      <i class="fa fa-file-word-o fa-2x"></i> 
      <% elsif project.file2_type == 1 %>
      <i class="fa fa-file-excel-o fa-2x"></i> 
      <% elsif project.file2_type == 2 %>
      <i class="fa fa-file-powerpoint-o fa-2x"></i> 
      <% else %>
      <i class="fa fa-file-pdf-o fa-2x"></i> 
      <% end %>
      &nbsp; <%= project.file2_title %>
    </a><br/>
    <% end %>

    <% if project.file3? %>
    <a href="<%= project.file1.url() %>">
      <% if project.file3_type == 0 %>
      <i class="fa fa-file-word-o fa-2x"></i> 
      <% elsif project.file3_type == 1 %>
      <i class="fa fa-file-excel-o fa-2x"></i> 
      <% elsif project.file3_type == 2 %>
      <i class="fa fa-file-powerpoint-o fa-2x"></i> 
      <% else %>
      <i class="fa fa-file-pdf-o fa-2x"></i> 
      <% end %>
      &nbsp; <%= project.file3_title %>
    </a><br/>
    <% end %>

    <% if project.file4? %>
    <a href="<%= project.file1.url() %>">
      <% if project.file4_type == 0 %>
      <i class="fa fa-file-word-o fa-2x"></i> 
      <% elsif project.file4_type == 1 %>
      <i class="fa fa-file-excel-o fa-2x"></i> 
      <% elsif project.file4_type == 2 %>
      <i class="fa fa-file-powerpoint-o fa-2x"></i> 
      <% else %>
      <i class="fa fa-file-pdf-o fa-2x"></i> 
      <% end %>
      &nbsp; <%= project.file4_title %>
    </a><br/>
    <% end %>
  </div>
  <br/><br/>
</div>
<% end %>

app/views/projects/_project1.html.erb
<div class ="row portfolio">
<% @user.projects.each do |project| %>
	<% if project.file2? %>
		 <a href="<%= project.file2.url() %>">
 	<% else %>
		<a href="<%= project.url %>">
	<% end %>
		<div class = "client">
			<%= image_tag project.file1.url %>
			<div class = "small-12 columns text">
				<h2> <b><%= project.title %></b> </h2>
				<p> <%= project.paragraph %> </p>
			</div>
		</div>
	</a>
<% end %>

app/views/projects/_projectSchoolView.erb
<% @school.projects.order("RANDOM()").each do |project| %>
<div class = "small-12 small-centered columns instance">
  <h5> <%= link_to project.user.homepage_info.homepage_display_name, user_path(project.user)  %> </h5>
  <h4> <%= project.title %> </h4>
  <p> <%= project.paragraph %></p>

  <% if project.file1? %>
  <a href="<%= project.file1.url() %>">
    <% if project.file1_type == 0 %>
    <i class="fa fa-file-word-o fa-2x"></i> 
    <% elsif project.file1_type == 1 %>
    <i class="fa fa-file-excel-o fa-2x"></i> 
    <% elsif project.file1_type == 2 %>
    <i class="fa fa-file-powerpoint-o fa-2x"></i> 
    <% else %>
    <i class="fa fa-file-pdf-o fa-2x"></i> 
    <% end %>
    &nbsp; <%= project.file1_title %>
  </a><br/>
  <% end %>

  <% if project.file2? %>
  <a href="<%= project.file1.url() %>">
    <% if project.file2_type == 0 %>
    <i class="fa fa-file-word-o fa-2x"></i> 
    <% elsif project.file2_type == 1 %>
    <i class="fa fa-file-excel-o fa-2x"></i> 
    <% elsif project.file2_type == 2 %>
    <i class="fa fa-file-powerpoint-o fa-2x"></i> 
    <% else %>
    <i class="fa fa-file-pdf-o fa-2x"></i> 
    <% end %>
    &nbsp; <%= project.file2_title %>
  </a><br/>
  <% end %>

  <% if project.file3? %>
  <a href="<%= project.file1.url() %>">
    <% if project.file3_type == 0 %>
    <i class="fa fa-file-word-o fa-2x"></i> 
    <% elsif project.file3_type == 1 %>
    <i class="fa fa-file-excel-o fa-2x"></i> 
    <% elsif project.file3_type == 2 %>
    <i class="fa fa-file-powerpoint-o fa-2x"></i> 
    <% else %>
    <i class="fa fa-file-pdf-o fa-2x"></i> 
    <% end %>
    &nbsp; <%= project.file3_title %>
  </a><br/>
  <% end %>

  <% if project.file4? %>
  <a href="<%= project.file1.url() %>">
    <% if project.file4_type == 0 %>
    <i class="fa fa-file-word-o fa-2x"></i> 
    <% elsif project.file4_type == 1 %>
    <i class="fa fa-file-excel-o fa-2x"></i> 
    <% elsif project.file4_type == 2 %>
    <i class="fa fa-file-powerpoint-o fa-2x"></i> 
    <% else %>
    <i class="fa fa-file-pdf-o fa-2x"></i> 
    <% end %>
    &nbsp; <%= project.file4_title %>
  </a><br/>
  <% end %>
</div>
<% end %>

app/views/projects/_projectUserView.erb
<h3 class = "edit-info-header"> Classmate Projects </h3>

<% @user.school.projects.order("RANDOM()").each do |project| %>
<div class = "small-12 columns instance">
  <h5> <%= link_to project.user.homepage_info.homepage_display_name, user_path(project.user)  %> </h5>
  <h4> <%= project.title %> </h4>
  <p> <%= project.paragraph %></p>

  <% if project.file1? %>
  <a href="<%= project.file1.url() %>">
    <% if project.file1_type == 0 %>
    <i class="fa fa-file-word-o fa-2x"></i> 
    <% elsif project.file1_type == 1 %>
    <i class="fa fa-file-excel-o fa-2x"></i> 
    <% elsif project.file1_type == 2 %>
    <i class="fa fa-file-powerpoint-o fa-2x"></i> 
    <% else %>
    <i class="fa fa-file-pdf-o fa-2x"></i> 
    <% end %>
    &nbsp; <%= project.file1_title %>
  </a><br/>
  <% end %>

  <% if project.file2? %>
  <a href="<%= project.file1.url() %>">
    <% if project.file2_type == 0 %>
    <i class="fa fa-file-word-o fa-2x"></i> 
    <% elsif project.file2_type == 1 %>
    <i class="fa fa-file-excel-o fa-2x"></i> 
    <% elsif project.file2_type == 2 %>
    <i class="fa fa-file-powerpoint-o fa-2x"></i> 
    <% else %>
    <i class="fa fa-file-pdf-o fa-2x"></i> 
    <% end %>
    &nbsp; <%= project.file2_title %>
  </a><br/>
  <% end %>

  <% if project.file3? %>
  <a href="<%= project.file1.url() %>">
    <% if project.file3_type == 0 %>
    <i class="fa fa-file-word-o fa-2x"></i> 
    <% elsif project.file3_type == 1 %>
    <i class="fa fa-file-excel-o fa-2x"></i> 
    <% elsif project.file3_type == 2 %>
    <i class="fa fa-file-powerpoint-o fa-2x"></i> 
    <% else %>
    <i class="fa fa-file-pdf-o fa-2x"></i> 
    <% end %>
    &nbsp; <%= project.file3_title %>
  </a><br/>
  <% end %>

  <% if project.file4? %>
  <a href="<%= project.file1.url() %>">
    <% if project.file4_type == 0 %>
    <i class="fa fa-file-word-o fa-2x"></i> 
    <% elsif project.file4_type == 1 %>
    <i class="fa fa-file-excel-o fa-2x"></i> 
    <% elsif project.file4_type == 2 %>
    <i class="fa fa-file-powerpoint-o fa-2x"></i> 
    <% else %>
    <i class="fa fa-file-pdf-o fa-2x"></i> 
    <% end %>
    &nbsp; <%= project.file4_title %>
  </a><br/>
  <% end %>
</div>
<% end %>

app/views/projects/edit.html.erb
<div class = "row edit-page">
	<%= render 'application/sideNav'%>
	<div class = "small-12 medium-9 columns form-yield no-padding">
		<%= render 'application/topNav' %>
	    <%= render 'application/alerts' %>

	    <div class = "small-12 medium-9 columns edit-content-section">
			<div class = "edit-info-header">
				<h4> Edit Project Info </h4>
				<a href="#" data-reveal-id="instructModal">
					<i class="fa fa-info-circle"></i>&nbsp;Help
				</a>
			</div>

			<%= render 'form0' %>

			<%= render 'application/instructions_project' %>
		</div>
	</div>
</div>

app/views/projects/index.html.erb
<div class = "row edit-page">
    <%= render 'application/sideNav'%>
    <div class = "small-12 medium-9 columns form-yield no-padding">
        <%= render 'application/topNav' %>
        <%= render 'application/alerts' %>

        <div class = "small-12 medium-9 columns edit-content-section">
            <div class = "edit-info-header">
                <h4> Edit Projects </h4>
                <a href="#" data-reveal-id="instructModal">
                    <i class="fa fa-info-circle"></i>&nbsp;Help
                </a>
            </div>
                <%= button_to "New Project", new_project_path, :class => "button", :method => :get %>
    <br/>
    <br/>
    <%= render 'showcases/projects_edit_view' %>
    <br/>
    <br/>

    <% if current_user.projects != nil %>
      <a href="#" data-reveal-id="previewModal" class = "button alt3">View</a>
      <a href="/articles" class = "buttonNext"> Next  <i class="fa fa-arrow-right"></i> </a>
    <% end %>


     <%= render 'application/instructions_showcase' %>
     <%= render 'application/preview_showcase' %>
  </div>
</div>

app/views/projects/new.html.erb
<div class = "row edit-page">
	<%= render 'application/sideNav'%>
	<div class = "small-12 medium-9 columns form-yield no-padding">
		<%= render 'application/topNav' %>
	    <%= render 'application/alerts' %>

	    <div class = "small-12 medium-9 columns edit-content-section">
			<div class = "edit-info-header">
				<h4> New Project  </h4>
				<a href="#" data-reveal-id="instructModal">
					<i class="fa fa-info-circle"></i>&nbsp;Instructions
				</a>
			</div>

			<%= render 'form0' %>

			<%= render 'application/instructions_project' %>
		</div>
	</div>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>